# Generated by Django 2.2 on 2019-10-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('phone_number', models.CharField(max_length=12)),
                ('messages_received', models.IntegerField(default=0)),
            ],
        ),
    ]
